In [2]:
#1. Write a NumPy program to generate five random numbers from the normal distribution.
import numpy as np
x=np.random.normal(size=5)
x

array([-0.95681299, -0.64654999,  0.71748189,  1.20892149,  1.13077688])

In [4]:
#Write a NumPy program to generate six random integers between 10 and 30. Go to the editor
import numpy as np
num=np.random.randint(10,21,size=6)
num

array([15, 10, 18, 12, 13, 12])

In [17]:
#Write a NumPy program to create a 3x3x3 array with random values.
import numpy as np
num=np.random.random((3,3,3))
num

array([[[0.50429985, 0.01055385, 0.62841131],
        [0.30354364, 0.84838559, 0.48301847],
        [0.18161336, 0.34477106, 0.25446545]],

       [[0.79725716, 0.1989899 , 0.78064005],
        [0.65053814, 0.4295486 , 0.48876254],
        [0.51807499, 0.38786174, 0.71348648]],

       [[0.54823162, 0.32220028, 0.23461219],
        [0.32842838, 0.4232057 , 0.5398338 ],
        [0.66044576, 0.85505257, 0.4858467 ]]])

In [24]:
#Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.
import numpy as np
x=np.random.random((5,5))
x

array([[0.0753525 , 0.18988259, 0.71522838, 0.90776355, 0.94784647],
       [0.0214021 , 0.37536362, 0.37381492, 0.24398623, 0.64104724],
       [0.87374556, 0.7120413 , 0.44881377, 0.97404081, 0.34468048],
       [0.06526679, 0.13278335, 0.02526801, 0.74547677, 0.25349483],
       [0.11417646, 0.68952103, 0.47013545, 0.24816676, 0.93492198]])

In [23]:
a=x.max()
a

0.9820693041710868

In [22]:
b=x.min()
b

0.03848745727704184

In [25]:
#Write a NumPy program to create a random 10x4 array
import numpy as np
x=np.random.random((10,4))
x

array([[0.78552552, 0.03321141, 0.1650028 , 0.60653507],
       [0.42118361, 0.79243747, 0.57908004, 0.73374733],
       [0.50347526, 0.58515702, 0.3522935 , 0.60502814],
       [0.96848504, 0.7225067 , 0.60771182, 0.45496919],
       [0.69695475, 0.58792607, 0.44457341, 0.7044    ],
       [0.86667264, 0.84376641, 0.68309596, 0.77364822],
       [0.08965369, 0.83421165, 0.07115034, 0.6081686 ],
       [0.65015358, 0.98086515, 0.21777227, 0.03473126],
       [0.46237923, 0.00780734, 0.38464768, 0.0125003 ],
       [0.41112875, 0.26122886, 0.70434044, 0.40225122]])

In [29]:
#extract the first five rows of the array and store them into a variable.
y=x[:5]
y

array([[0.78552552, 0.03321141, 0.1650028 , 0.60653507],
       [0.42118361, 0.79243747, 0.57908004, 0.73374733],
       [0.50347526, 0.58515702, 0.3522935 , 0.60502814],
       [0.96848504, 0.7225067 , 0.60771182, 0.45496919],
       [0.69695475, 0.58792607, 0.44457341, 0.7044    ]])

In [5]:
#Write a NumPy program to shuffle numbers between 0 and 10 (inclusive).
import numpy as np
x=np.arange(0,11)
np.random.shuffle(x)
x

array([ 5,  9,  7,  8,  4,  0,  6,  1, 10,  3,  2])

In [10]:
#using permutations
import numpy as np
x=np.random.permutation(11)
x

array([ 3,  8,  2,  6,  9,  1,  0,  7,  4, 10,  5])

In [13]:
# Write a NumPy program to normalize a 3x3 random matrix
import numpy as np
x=np.random.random((3,3))
print("before normalization")
x

before normalization


array([[0.43141144, 0.42998835, 0.70907913],
       [0.62339514, 0.81456785, 0.21953946],
       [0.78085966, 0.8169382 , 0.30202225]])

In [10]:
y=x.max()
y

0.8616572609684167

In [12]:
print("after normalization:")
print(x/y)

after normalization:
[[0.40008179 0.96816398 0.62917142]
 [0.61601461 0.71403938 0.93653277]
 [0.71687598 1.         0.8560681 ]]


In [16]:
#Write a NumPy program to create a random vector of size 10 and sort it.
import numpy as np
x=np.random.random(10)
x

array([0.52941622, 0.78104179, 0.95907391, 0.09717069, 0.49098445,
       0.24731514, 0.75152101, 0.93250237, 0.56287471, 0.10450647])

In [17]:
print("after sorting:")
x.sort()
x

after sorting:


array([0.09717069, 0.10450647, 0.24731514, 0.49098445, 0.52941622,
       0.56287471, 0.75152101, 0.78104179, 0.93250237, 0.95907391])

In [22]:
#Write a NumPy program to check two random arrays are equal or not
import numpy as np
x=np.array([1,2,3])
y=np.array([1,2,3])
print(x)
print(y)
equal=np.allclose(x,y)
print("enter array is equal or not:")
print(equal)

[1 2 3]
[1 2 3]
enter array is equal or not:
True


In [23]:
#Write a NumPy program to create random vector of size 15 and replace the maximum value by -1.
import numpy as np
x=np.random.random(15)
x

array([0.40016551, 0.7254091 , 0.90301209, 0.97079817, 0.62800161,
       0.02425961, 0.25857304, 0.57162324, 0.89801575, 0.90592431,
       0.74597306, 0.63218885, 0.06069928, 0.54511888, 0.3417215 ])

In [33]:
# x[3]=-1
# x
x[x.argmax()]=-1
x

array([ 0.40016551,  0.7254091 , -1.        , -1.        ,  0.62800161,
        0.02425961,  0.25857304,  0.57162324,  0.89801575, -1.        ,
        0.74597306,  0.63218885,  0.06069928,  0.54511888,  0.3417215 ])

In [1]:
#Write a NumPy program to find point by point distances of a random vector with shape (10,2).
#representing coordinates.
import numpy as np
x=np.random.random((10,2))
x

array([[0.59356241, 0.14115558],
       [0.66829002, 0.10872032],
       [0.4602916 , 0.59802588],
       [0.22091859, 0.47369737],
       [0.95814699, 0.2610781 ],
       [0.68101635, 0.97726369],
       [0.00816619, 0.76053427],
       [0.8597928 , 0.76987776],
       [0.17495098, 0.55221336],
       [0.10486806, 0.69861951]])

In [8]:
#Write a NumPy program to find the most frequent value in an array.
import numpy as np
x=np.array([1,5,6,7,8,3,4,1,2,3,4,5,1])
print(x)
print("maximum is:")
print(np.bincount(x).argmax())

[1 5 6 7 8 3 4 1 2 3 4 5 1]
maximum is:
1


In [11]:
#Write a NumPy program to find the closest value (to a given scalar) in an array. 
import numpy as np
x=np.random.randint((3,3))
x

array([1, 0])