In [1]:
#numpy basic or numpy initilization.
import numpy as np
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
import numpy as np
arr=np.arange(1,6)
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [3]:
np.exp(arr)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [4]:
#Random array(normal distrubution).
import numpy as np
a=np.random.randn(10)
#a=np.random.random((1,10))
a

array([-1.12005864,  0.35680345, -2.14420416,  0.75345412, -0.29821669,
       -2.11037714, -1.34629842, -2.09362323,  1.5968864 ,  0.8878222 ])

In [9]:
import numpy as np
b=np.random.randn(10)
b

array([-2.03755828, -0.87349884,  0.51320414,  0.51342089,  1.54223027,
        1.02252731,  2.29811602, -0.7656001 ,  0.70701259,  0.34874114])

In [10]:
#addition of two numpy 
np.add(a,b)

array([-3.06577776, -2.28099881,  1.07149925,  0.01873849,  1.70097597,
        1.25868539,  1.25399714,  0.24853764,  0.8536557 ,  1.30731738])

In [12]:
#printing a maximum value from a and b:
np.maximum(a,b)

array([-1.02821948, -0.87349884,  0.55829511,  0.51342089,  1.54223027,
        1.02252731,  2.29811602,  1.01413774,  0.70701259,  0.95857624])

In [13]:
#printing a minimum value from a and b:
np.minimum(a,b)

array([-2.03755828, -1.40749997,  0.51320414, -0.4946824 ,  0.15874569,
        0.23615808, -1.04411889, -0.7656001 ,  0.14664312,  0.34874114])

In [23]:
#generating a random number
import numpy as np
arr=np.random.randint(10)
arr

1

In [44]:
#creating a random matrix
import numpy as np
ran=np.random.randint(1,10,15).reshape(5,3)#here 15 is number of elements 15.i.e.(5x3=15)
ran

array([[2, 7, 4],
       [8, 4, 9],
       [7, 4, 1],
       [2, 9, 2],
       [9, 5, 8]])

In [47]:
#getting a maximum value from a matrix
ran.max()

9

In [46]:
#getting a minimum value from a matrix.
ran.min()

1

In [50]:
#adding two list
list1=[1,2,3,4]
list2=[5,6,7,8]
sum=[list1,list2]
sum

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [51]:
#adding two list using numpy.
arr=np.array(sum)
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [54]:
#creating 0's matrix
import numpy as np
x=np.zeros((4,3))
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [56]:
#creating 1's matrix
import numpy as np
x=np.ones((3,3),dtype=int)
x

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [61]:
#creating a empty elements matrix.
import numpy as np
x=np.empty((3,4),dtype=int)
x

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [64]:
import numpy as np
np.full((5,3),[1,2,3])

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [5]:
#digonal array
np.eye((4),dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [7]:
#identity matrix with nxn array
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [74]:
#accessing only diagnoal elements.
np.diag(np.identity(4))

array([1., 1., 1., 1.])

In [9]:
#calculating a length of a array. 
import numpy as np
x=np.arange(1,50,2)
len(x)

25

In [11]:
#creating a matrix with it's length as a total number. 
np.arange(1,50,2).reshape(5,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [84]:
#creating a matrix with it's length as a total number.
import numpy as np
np.arange(0,30).reshape(2,15)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [85]:
#transpose matrix
np.arange(0,30).reshape(2,15).T

array([[ 0, 15],
       [ 1, 16],
       [ 2, 17],
       [ 3, 18],
       [ 4, 19],
       [ 5, 20],
       [ 6, 21],
       [ 7, 22],
       [ 8, 23],
       [ 9, 24],
       [10, 25],
       [11, 26],
       [12, 27],
       [13, 28],
       [14, 29]])

In [86]:
#ravel function
np.arange(0,30).ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [90]:
#calculating a dimension of a matrix
import numpy as np
np.arange(0,30).reshape(5,6).T.ndim

2

In [9]:
#to know the datatype of list.
import numpy as np
x=np.array([3,5,6,7])
x.dtype

dtype('int32')

In [3]:
import numpy as np
y=np.array([4.6,4.3,7.8,5])
y.dtype

dtype('float64')

In [6]:
#converting a float into a int datatype.
y.astype(x.dtype)

array([4, 4, 7, 5])

In [22]:
#change its value to float value but not possible in int.
import numpy as np
arr=np.array(["3.2","6.7","4.5"])
arr=arr.astype(float)
arr

array([3.2, 6.7, 4.5])

In [20]:
#but after converting a string to float then only we can convert it into int.
arr=arr.astype(int)
arr

array([3, 6, 4])

In [26]:
#2-D array in numpy.
import numpy as np
xy=np.array([[1,2,3],[4,5,6],[7,8,9]])
xy

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
#print those which are greater than 4.
[xy<4]

[array([[ True,  True,  True],
        [False, False, False],
        [False, False, False]])]

In [28]:
#return only true value in a 1-D array.
xy[xy<4]

array([1, 2, 3])

In [30]:
#getting the value that we want.
xy[1][2]

6

In [36]:
#operations in particular row.
xy[1][xy[1]>4]

array([5, 6])

In [3]:
#creating first 2-D matrix
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
#creating second 2-D matrix
arr2=np.array([[7,8,9],[1,2,3],[4,5,6]])
arr2

array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [7]:
#operations on matrix
arr1*arr1

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [8]:
arr1+arr2

array([[ 8, 10, 12],
       [ 5,  7,  9],
       [11, 13, 15]])

In [9]:
arr2-arr1

array([[ 6,  6,  6],
       [-3, -3, -3],
       [-3, -3, -3]])

In [12]:
#reciprocal of elements in matrix.
1/arr1

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667],
       [0.14285714, 0.125     , 0.11111111]])

In [13]:
#slicing of array
import numpy as np
arr=np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr[:5]=55
arr

array([55, 55, 55, 55, 55,  5,  6,  7,  8,  9, 10])

In [15]:
slice_arr=arr[:5]
slice_arr

array([55, 55, 55, 55, 55])

In [17]:
slice_arr[:]=100
slice_arr

array([100, 100, 100, 100, 100])

In [18]:
arr
#here we found that 100's is include in o/p beacuse it uses call by refrence and more than one elements is use.

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [26]:
#to avoid this multiple 100's we can use copy function
import numpy as np
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr_copy=arr.copy()
arr_copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
x=arr_copy[:6]
x

array([1, 2, 3, 4, 5, 6])

In [30]:
x[:6]=66
x

array([66, 66, 66, 66, 66, 66])

In [32]:
#here we found that our actual array that is arr that is not effect by certain 
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
#numpy array shape
import numpy as np
arr=np.array([1,2,3],ndmin=5)#it create array with 5 dimension.
arr

array([[[[[1, 2, 3]]]]])

In [8]:
#numpy array reshape
import numpy as np
arr=np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [13]:
import numpy as np
arr=np.arange(1,21).reshape(5,2,2)
arr

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20]]])

In [18]:
import numpy as np
arr=np.arange(1,9).reshape(2,2,-1)
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [19]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]]).reshape(-1)#join two sub array.
arr

array([1, 2, 3, 4, 5, 6])

In [21]:
#numpy array iterating
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [22]:
#iterate on each scaler elements
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    for y in x:
        print(y)


1
2
3
4
5
6


In [24]:
#iterating 3-D array
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9


In [6]:
#numpy array join
import numpy as np
x1=np.array([1,2,3])
x2=np.array([4,5,6])
print(np.concatenate((x1,x2)))

[1 2 3 4 5 6]


In [8]:
#join 2-D array along rows.
import numpy as np
x1=np.array([[1,2],[3,4]])
x2=np.array([[5,6],[7,8]])
x=np.concatenate((x1,x2),axis=1)
print(x)

[[1 2 5 6]
 [3 4 7 8]]


In [9]:
#joining array using stack function(1-D array.)
import numpy as np
x1=np.array([1,2,3])
x2=np.array([4,5,6])
print(np.stack((x1,x2),axis=1))

[[1 4]
 [2 5]
 [3 6]]


In [13]:
#joining array using hstack function in row wise(1-D array.)
import numpy as np
x1=np.array([1,2,3])
x2=np.array([4,5,6])
print(np.hstack((x1,x2)))

[1 2 3 4 5 6]


In [14]:
#vstack function()
import numpy as np
x1=np.array([1,2,3])
x2=np.array([4,5,6])
print(np.vstack((x1,x2)))

[[1 2 3]
 [4 5 6]]


In [15]:
#dstack function()
import numpy as np
x1=np.array([1,2,3])
x2=np.array([4,5,6])
print(np.dstack((x1,x2)))

[[[1 4]
  [2 5]
  [3 6]]]


In [7]:
#it divide array into a equal half
import numpy as np
x1=np.arange(1,11)
x2=np.array_split(x1,5)
print(x2)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]


In [8]:
print(x2[1])

[3 4]


In [15]:
#split 2-D array
import numpy as np
x1=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
x2=np.array_split(x1,2)
x2

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

In [16]:
import numpy as np
x1=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
x2=np.array_split(x1,2,axis=1)
x2

[array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12]])]

In [17]:
#searching in array
import numpy as np
arr=np.array([1,2,3,4,5,6,4])
x1=np.where(arr==4)#it return the loc of 4.
x1

(array([3, 6], dtype=int64),)

In [18]:
#find the index where value are even.
import numpy as np
arr=np.array([1,3,4,56,7,8,2,4,6,9])
x1=np.where(arr%2==0)#it return even value index.
print(x1)

(array([2, 3, 5, 6, 7, 8], dtype=int64),)


In [22]:
#search sort function()
import numpy as np
arr=np.array([1,3,5,6,7,8])
x1=np.searchsorted(arr,7)
x1

4

In [23]:
import numpy as np
arr=np.array([1,5,6,7,8])
x1=np.searchsorted(arr,[3,4,9])#it return the index to be inserted.
x1

array([1, 1, 5], dtype=int64)

In [24]:
#array sorting
import numpy as np
arr=np.array([1,6,3,2])
print(np.sort(arr))

[1 2 3 6]


In [25]:
import numpy as np
arr=np.array(["bibek","apple","cat","ant"])
print(np.sort(arr))

['ant' 'apple' 'bibek' 'cat']


In [27]:
#sorting 2-D array
import numpy as np
arr=np.array([[1,4,2],[7,4,8]])
print(np.sort(arr))

[[1 2 4]
 [4 7 8]]


In [31]:
#random number int
from numpy import random
num=random.randint(1,11)
print(num)
num1=random.rand()#it returns random float number.
print(num1)

1
0.5639044608734195


In [36]:
#generate random array
from numpy import random
arr=random.randint(1,11,size=(5))
arr

array([ 2, 10,  1,  3,  4])

In [44]:
#generate random 2-D array
from numpy import random
arr=random.randint(1,100,size=(5,3))
arr

array([[70, 21,  6],
       [95, 82, 41],
       [66,  5, 90],
       [47, 87, 68],
       [70,  8, 29]])

In [49]:
#choice
from numpy import random
arr=random.choice([3,6,8,9])
arr

8

In [50]:
#adding two array in numpy.
import numpy as np
x1=np.array([1,2,3])
x2=np.array([4,5,6])
print(x1+x2)

[5 7 9]


In [55]:
#adding two list without numpy
x1=[1,2,3]
x2=[4,5,6]
x3=[]
for i,j in zip(x1,x2):
    x3.append(i+j)
print(x3)

[5, 7, 9]


In [3]:
import numpy as np
arr=np.array([[5,10,15],[20,25,30],[35,40,45]])
print(arr[:2,1:])
print(arr[:2,0])

[[10 15]
 [25 30]]
[ 5 20]


In [13]:
import numpy as np
arr=np.arange(0,50).reshape(10,5)
print(arr)
print(arr[[1,4,8],0])
print(arr[[1,4,8],[0,1,2]])#it act as like mapping.
print(arr[[1,4,8],0:7])#print all the elements that are present in respective location.

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
[ 5 20 40]
[ 5 21 42]
[[ 5  6  7  8  9]
 [20 21 22 23 24]
 [40 41 42 43 44]]


In [17]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
x=np.dot(arr.T,arr)
x

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 66,  78,  90],
       [ 78,  93, 108],
       [ 90, 108, 126]])

In [18]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [29]:
import numpy as np
arr=np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [27]:
print(arr.ravel())#reval function convert this array into 1-D array.

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


In [30]:
#creating 3-D matrix
import numpy as np
arr=np.arange(1,51).reshape(5,5,2)
arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]],

       [[21, 22],
        [23, 24],
        [25, 26],
        [27, 28],
        [29, 30]],

       [[31, 32],
        [33, 34],
        [35, 36],
        [37, 38],
        [39, 40]],

       [[41, 42],
        [43, 44],
        [45, 46],
        [47, 48],
        [49, 50]]])

In [36]:
import numpy as np
arr=np.array([[1,2,3,4]])
arr.swapaxes(1,0)#changing it's axis.

array([[1],
       [2],
       [3],
       [4]])

In [37]:
import numpy as np
A=np.array([1,2,3,4])
B=np.array([100,200,300,400])
condition=np.array([True,True,False,False])
ans=[(A_val if cond else B_val)for A_val,B_val,cond in zip(A,B,condition)]
ans

[1, 2, 300, 400]

In [38]:
ans1=np.where(condition,A,B)
ans1

array([  1,   2, 300, 400])

In [42]:
import numpy as np
arr=np.arange(1,10).reshape(3,3)
print(arr)
arr.sum()#it returns sum of all the elements that are present in matrix.

[[1 2 3]
 [4 5 6]
 [7 8 9]]


45

In [43]:
arr.sum(0)#sum of axis 0.

array([12, 15, 18])

In [44]:
arr.sum(1)#sum of axis 1.

array([ 6, 15, 24])

In [47]:
arr.mean()

5.0